# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 513db6e925d2e1c42e44f7fd3e78f7326681a433d793beaf25e7cb7219122b9ea111d89b46984bc5c26499ac4770865919714cdc9ba0851738fccb448c95f4a3

test:
  secret_key_base: d71acf491dd18a58e33ab84d19c306f7cf015cebdd8acb71ef60874da52dcda57e99873c25c76f5c0f3b5c7bc8ac2bd5147221f7f2f7e5059941c64bed6112c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
